export const SET_PROJECTSETTING_LOADER = "SET_PROJECTSETTING_LOADER";
export const SET_PROJECTSETTING = "SET_PROJECTSETTING";
export const UPDATE_PROJECTSETTING = "UPDATE_PROJECTSETTING";
export const DELETE_PROJECTSETTING = "DELETE_PROJECTSETTING";
export const ADD_PROJECTSETTING = "ADD_PROJECTSETTING";
